# Generated by Django 3.2.7 on 2022-02-19 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_alter_bookingrooms_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrooms',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date(2022, 2, 19)),
        ),
    ]
