# Generated by Django 3.2.7 on 2022-02-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='applied_for',
            field=models.CharField(default='backend', max_length=50),
        ),
    ]
