# Generated by Django 3.2.7 on 2022-02-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_excelfileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Careerdetails',
        ),
        migrations.DeleteModel(
            name='ExcelFileUpload',
        ),
    ]
