# Generated by Django 3.2.7 on 2021-10-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookedCab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PassName', models.CharField(max_length=40)),
                ('PassPhone', models.CharField(max_length=40)),
                ('PassPickup', models.CharField(max_length=40)),
                ('PassDrop', models.CharField(max_length=40)),
                ('Car', models.CharField(max_length=40)),
                ('PassDate', models.CharField(max_length=40)),
                ('PassTime', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='cabowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CabOwnerName', models.CharField(max_length=40)),
                ('CabOwnerContact', models.CharField(max_length=20)),
                ('CabOwnerPhoto', models.FileField(null=True, upload_to='media/')),
                ('CabOwnerAdhar', models.FileField(null=True, upload_to='media/')),
                ('CabOwnerPan', models.FileField(null=True, upload_to='media/')),
                ('vechileType', models.CharField(max_length=15)),
                ('CabName', models.CharField(max_length=50)),
                ('CabContactNo', models.CharField(max_length=15)),
                ('CabNumberPlate', models.CharField(max_length=30)),
                ('CabPhoto', models.FileField(null=True, upload_to='media/')),
                ('CabNumberPhoto', models.FileField(null=True, upload_to='media/')),
                ('Cabregistration', models.FileField(null=True, upload_to='media/')),
                ('CabAllData', models.FileField(null=True, upload_to='media/')),
            ],
        ),
    ]
