# Generated by Django 3.2.7 on 2021-10-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0002_cabowner_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabowner',
            name='Email',
            field=models.CharField(default=False, max_length=40),
        ),
    ]
