# Generated by Django 3.2.7 on 2021-11-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0003_cabowner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabowner',
            name='CabOwnerContact',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
