# Generated by Django 3.2.8 on 2021-11-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0004_alter_cabowner_cabownercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcab',
            name='booking_id',
            field=models.CharField(default='', max_length=40),
        ),
    ]
