# Generated by Django 3.2.8 on 2021-11-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0007_bookedcab_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedcab',
            old_name='published',
            new_name='payment',
        ),
        migrations.AddField(
            model_name='bookedcab',
            name='bank_name_200',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bookedcab',
            name='bank_transaction_id_200',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bookedcab',
            name='payment_mode_200',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bookedcab',
            name='transaction_date_200',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bookedcab',
            name='transaction_id_200',
            field=models.CharField(default='', max_length=50),
        ),
    ]
