# Generated by Django 3.2.7 on 2022-02-16 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0008_auto_20211102_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='addcab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_id', models.CharField(default='', max_length=30)),
                ('cab_name', models.CharField(default='', max_length=100)),
                ('category', models.CharField(max_length=30)),
                ('PassPickup', models.CharField(max_length=40)),
                ('PassDrop', models.CharField(max_length=40)),
                ('discount', models.CharField(max_length=30)),
                ('description', models.CharField(default='Best in class cab service with AC facilities .Enjoy your journey with your loved ones.', max_length=3000)),
                ('email', models.CharField(max_length=50)),
                ('date', models.CharField(default='', max_length=15)),
                ('price', models.CharField(max_length=30)),
                ('image1', models.FileField(upload_to='media/')),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=30)),
                ('cab_registration_no', models.CharField(max_length=10)),
                ('contact_no', models.IntegerField()),
                ('car_type', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('booking_id', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='bookedcab',
            name='cab_id',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='bookedcab',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookedcab',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookedcab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 18, 27, 9, 747652)),
        ),
        migrations.AddField(
            model_name='bookedcab',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookedcab',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookedcab',
            name='total',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookedcab',
            name='booking_id',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
