# Generated by Django 3.2.7 on 2022-02-19 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0010_auto_20220219_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedcab',
            old_name='payment_link',
            new_name='advpay_link',
        ),
        migrations.AlterField(
            model_name='bookedcab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 19, 23, 7, 826562)),
        ),
    ]
