# Generated by Django 3.2.7 on 2022-02-19 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0011_auto_20220219_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcab',
            name='advpay_price',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='bookedcab',
            name='advpay_link',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='bookedcab',
            name='bank_name_200',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='bookedcab',
            name='bank_transaction_id_200',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='bookedcab',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 1, 32, 9, 388550)),
        ),
        migrations.AlterField(
            model_name='bookedcab',
            name='total',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='bookedcab',
            name='transaction_date_200',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='bookedcab',
            name='transaction_id_200',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
